export interface Booking_Data {
    guestName: string,
    guestEmail: string,
    guestPhone: string,
    alternatePhone: string,
    villaId: number,
    checkIn: string,
    checkOut: string,
    numberOfAdults: number,
    numberOfChildren: number,
    specialRequest: string,
    gstMode: string,
    gstOnBasePrice: boolean,
    gstOnExtraCharge: boolean,
    gstDays: number,
    bookingSource: string | null,
    customPrice: number,
    extraPersonCharge: number,
    discount: number,
    advancePaid: number,
};
